#!/bin/bash
echo "LivingRoom Node Start."
echo "Enter commands on the CLI, like:
	panid 0x1234
	ifconfig up
	thread start
	thread stop
	exit

	state
	ipaddr
	ping IPv6
	
	coap start
	coap resource light_sta
	coap put gwAddr light_sta con 1
"

cd /mnt/hgfs/Shared/openthread
./output/x86_64-unknown-linux-gnu/bin/ot-cli-ftd 2