#!/bin/bash
echo "Opentread Installing."
echo "Enter commands on the cmd:

- Install python-software-properties
	sudo apt-get install -y python-software-properties
	sudo add-apt-repository -y ppa:terry.guo/gcc-arm-embedded
	sudo apt-get update -qq

- Install packages needed for wpantund build and runtime
	sudo apt-get install -y build-essential git make autoconf autoconf-archive automake dbus libtool gcc g++ gperf flex bison texinfo ncurses-dev libexpat-dev python sed python-pip gawk libreadline6-dev libreadline6 libdbus-1-dev libboost-dev
	sudo apt-get install -y --force-yes gcc-arm-none-eabi
	sudo pip install pexpect

- Install wpantund
	cd /mnt/hgfs/Shared/wpantund
	./configure --sysconfdir=/etc
	make
	sudo make install

- Install OpenThread
		$ cd /mnt/hgfs/Shared/openthread
		$ ./bootstrap

- Build OpenThread Application using the POSIX example.

		$ cd /mnt/hgfs/Shared/openthread
		$ make -f examples/Makefile-posix
"