#!/bin/bash
echo "wpanctl Start."
echo "Enter commands on the CLI, like:
	scan
	set Network:Key --data 00112233445566778899aabbccddeeff
	join 1
	join 1 -T 2 -p 0x1234 -x 0xDEAD00BEEF00CAFE -c 11

	status
	leave
	quit
"

sudo /usr/local/bin/wpanctl -I utun6
