#!/bin/bash
# global configurations

HOME_PATH="/home/pi"
BOOT_SYS_FILE="/etc/rc.local"

# for creating Thread Network
THREAD_INTERFACE_NAME="utun6"
THREAD_NETWORK_KEY="00112233445566778899AABBCCDDEEFF"
THREAD_CHANNEL="11"
THREAD_PANID="0x1234"

# for EMSK borad
SOCKET_PATH="/dev/ttyUSB1"

# for K64/NRF52840 board
# SOCKET_PATH="/dev/ttyACM0"